# <https://travis-ci.org/Tiendil/smart-imports>

language: python

#########################
# required by python 3.7
sudo: required
dist: xenial
#########################

os:
  - linux

python:
  - 3.5
  - 3.6
  - 3.7

cache: pip

install:
  - pip install .

script: python -m unittest discover -t . smart_imports

after_success:
    - pip install coveralls && coverage run --source=smart_imports setup.py test && coveralls
